version: "3"

services:
  db:
    image: mysql:${MYSQL_VERSION}
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "${MYSQL_PORT}:3306"
    volumes:
      - ./projects/${COMPOSE_PROJECT_NAME}/db:/var/lib/mysql

  backend:
    image: php:${PHP_VERSION}
    depends_on:
      - db
    ports:
      - "${WEB_BACKEND_PORT}:80"
    volumes:
      - ./projects/${COMPOSE_PROJECT_NAME}/backend:/var/www/html

  frontend:
    image: httpd
    ports:
      - "${WEB_FRONTEND_PORT}:80"
    volumes:
      - ./projects/${COMPOSE_PROJECT_NAME}/frontend:/usr/local/apache2/htdocs
