version: '3'

services:

  #FRONTEND
  httpd:
    image: httpd
    container_name: apache_frontend
    ports:
      - "81:80"
    volumes:
      - ${FRONTPATH}:/usr/local/apache2/htdocs
    networks:
      - frontend

  #BACKEND
  mysql:
    image: mysql:5.7
    container_name: mysql_backend
    environment:
      MYSQL_DATABASE: ${DATABASE}
      MYSQL_USER: ${USER}
      MYSQL_PASSWORD: ${PASSWORD}
      MYSQL_ROOT_PASSWORD: ${PASSWORD}
    ports:
      - "3307:3306"
    restart: always
    volumes:
      - ./backend/db:/var/lib/mysql
    networks:
      - backend
    env_file:
      - ./.env

  web:
    image: php:7.3-apache
    container_name: php_apache_backend
    ports:
      - "82:80"
    volumes:
      - ./backend/html:/var/www/html
    links:
      - mysql
    networks:
      - frontend
      - backend

networks:
  backend:
  frontend:
    driver: bridge
